language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage"
notifications:
  email:
    - tormozz48@gmail.com
    - yndx.tavria@yandex.ru
